@Replicate.Model(variants = [DtoVariant.DATA, DtoVariant.PATCH, DtoVariant.CREATE])
private interface UserAccount {
    // id is generated by the server, so it should not be in the CREATE request.
    @Replicate.Property(exclude = [DtoVariant.CREATE])
    val id: Uuid

    val email: String
}