public sealed interface <SchemaName>Schema {
    public data class Data(...) : <SchemaName>Schema, ...
    public data class CreateRequest(...) : <SchemaName>Schema, ...
    public data class PatchRequest(...) : <SchemaName>Schema, ...
}