public sealed interface <SchemaName>Schema {
    public sealed interface V1 : <SchemaName>Schema {
        public data class Data(...) : V1, ...
        public data class CreateRequest(...) : V1, ...
    }

    public sealed interface V2 : <SchemaName>Schema {
        public data class Data(...) : V2, ...
        public data class PatchRequest(...) : V2, ...
    }
}