// Generated by KReplica. Do not edit.
package io.availe.demo

import io.availe.models.KReplicaCreateVariant
import io.availe.models.KReplicaDataVariant
import io.availe.models.KReplicaPatchVariant
import io.availe.models.Patchable
import java.util.UUID

public sealed interface UserAccountSchema {
    public data class Data(
        public val id: UUID,
        public val email: String,
        public val displayName: String?,
    ) : UserAccountSchema, KReplicaDataVariant<UserAccount>

    public data class CreateRequest(
        public val email: String,
        public val displayName: String?,
    ) : UserAccountSchema, KReplicaCreateVariant<UserAccount>

    public data class PatchRequest(
        public val id: Patchable<UUID> = Patchable.Unchanged,
        public val email: Patchable<String> = Patchable.Unchanged,
        public val displayName: Patchable<String?> = Patchable.Unchanged,
    ) : UserAccountSchema, KReplicaPatchVariant<UserAccount>
}